inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Guardfile'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  ExcludedMethods:
    - describe
